module.exports = {
   abi: [
    {
       "inputs":[
          {
             "internalType":"uint256",
             "name":"index",
             "type":"uint256"
          }
       ],
       "name":"retrieve",
       "outputs":[
          {
             "components":[
                {
                   "internalType":"string",
                   "name":"name",
                   "type":"string"
                },
                {
                   "internalType":"uint256",
                   "name":"favoriteNumber",
                   "type":"uint256"
                }
             ],
             "internalType":"struct SimpleStorage.People",
             "name":"",
             "type":"tuple"
          }
       ],
       "stateMutability":"view",
       "type":"function"
    },
    {
       "inputs":[
          {
             "internalType":"string",
             "name":"_name",
             "type":"string"
          }
       ],
       "name":"searchFavoriteNumberPerPerson",
       "outputs":[
          {
             "internalType":"uint256",
             "name":"",
             "type":"uint256"
          }
       ],
       "stateMutability":"view",
       "type":"function"
    },
    {
       "inputs":[
          {
             "internalType":"string",
             "name":"_name",
             "type":"string"
          },
          {
             "internalType":"uint256",
             "name":"_favoriteNumber",
             "type":"uint256"
          }
       ],
       "name":"store",
       "outputs":[
          
       ],
       "stateMutability":"nonpayable",
       "type":"function"
    }
 ]
};